# action.yml
name: 'Prepare vault configuration'
description: 'Creates an empty vault secret folder if not yet existing and prepares credentials for the given service to access those credentials'
inputs:
    aws-access-key-id:
        description: 'AWS Access Key ID'
        required: false
    aws-secret-access-key:
        description: "AWS Secret Access Key"
        required: false
    service:
        description: "Name of the service"
        required: true
    environment:
        description: "Name of the environment"
        required: true
    vault-token: 
        description: "Vault token"
        required: true
    method:
        description: "The vault auth method to use, s3 or iam"
        required: false
        default: "s3"
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        VAULT_TOKEN: ${{ inputs.vault-token }}
    args:
        - ${{ inputs.service }}
        - ${{ inputs.environment }}
        - ${{ inputs.method }}
